<script lang="ts" setup>
/**
 * Third-party open-source attributions, rendered from `src/assets/notices.json`.
 *
 * That file is generated by `npm run generate:notices` and committed — see
 * scripts/generate-notices.mjs for how, and docs/FOOTER_AND_LEGAL_PLAN.md §9 for why. Grouped by
 * licence rather than listed flat: 642 alphabetical rows is a wall, whereas "these 400 are MIT" is
 * something a reader can actually use.
 */
import { ref } from 'vue'
import LegalPage from '@/components/LegalPage.vue'
import notices from '@/assets/notices.json'

interface Component {
  name: string
  version: string | null
  url: string | null
  ecosystem: string
}

interface LicenseGroup {
  license: string
  url: string | null
  components: Component[]
}

const groups = notices.licenses as LicenseGroup[]

// Collapsed by default: expanded, the MIT group alone is several hundred rows and the page becomes
// unnavigable. The <details> element gives keyboard and screen-reader behaviour for free.
const openGroups = ref(new Set<string>())

function toggle(license: string, open: boolean) {
  if (open) openGroups.value.add(license)
  else openGroups.value.delete(license)
}
</script>

<template>
  <LegalPage
    :intro="`Event Junkie is built on ${notices.componentCount} open-source components. Thank you to everyone who wrote them.`"
    title="Open-source notices"
  >
    <section>
      <h2>What this lists</h2>
      <p>
        Every dependency of this project — the backend's runtime libraries and the frontend's
        production packages, including their own transitive dependencies. It is generated from the
        build rather than maintained by hand, so it stays accurate as dependencies change.
      </p>
      <p>
        Two caveats, so the list is not read as more than it is. It covers what the project
        <em>depends on</em>, which is broader than what is served to your browser: bundling drops a
        good deal of it. And it records each component's licence rather than reproducing the full
        licence text or any <code>NOTICE</code> file the component ships — those travel with the
        packages themselves, at the source links below.
      </p>
    </section>

    <section>
      <h2>Our own code</h2>
      <p>
        Event Junkie's source is published under the Apache License 2.0 and is available in full at
        <a href="https://github.com/enorm-labs/event-checker" rel="noopener" target="_blank">
          github.com/enorm-labs/event-checker </a
        >.
      </p>
    </section>

    <section>
      <h2>Components by licence</h2>
      <details
        v-for="group in groups"
        :key="group.license"
        class="rounded-lg border border-border p-4"
        @toggle="toggle(group.license, ($event.target as HTMLDetailsElement).open)"
      >
        <summary class="cursor-pointer font-medium text-foreground">
          {{ group.license }}
          <span class="font-normal text-muted-foreground">
            — {{ group.components.length }}
            {{ group.components.length === 1 ? 'component' : 'components' }}
          </span>
        </summary>

        <p v-if="group.url" class="mt-2 text-sm">
          <a :href="group.url" rel="noopener" target="_blank"
            >Read the {{ group.license }} licence</a
          >
        </p>

        <!-- Rendered only while open: mounting every row up front is ~640 list items and a visible
             hitch on the first paint of this route. -->
        <ul v-if="openGroups.has(group.license)" class="mt-3 text-sm">
          <li v-for="component in group.components" :key="`${component.name}@${component.version}`">
            <a v-if="component.url" :href="component.url" rel="noopener" target="_blank">
              {{ component.name }}
            </a>
            <span v-else>{{ component.name }}</span>
            <span v-if="component.version" class="text-muted-foreground">
              {{ component.version }}
            </span>
          </li>
        </ul>
      </details>
    </section>
  </LegalPage>
</template>
