import { expect, test } from '@playwright/test'

/**
 * The crawler-facing surface: `/sitemap.xml`, `/robots.txt`, and the per-route annotations in the
 * head.
 *
 * The two files are generated by a Vite plugin (`scripts/seoFiles.ts`) that also serves them from
 * dev-server middleware, so these pass identically under `npm run dev` and `npm run preview`. The
 * head tags are checked in a real browser because they are written *after* the router resolves —
 * a unit test can only prove the function works, not that it runs.
 */

test('serves a sitemap listing every static page in both locales', async ({ request }) => {
  const response = await request.get('/sitemap.xml')

  expect(response.status()).toBe(200)
  expect(response.headers()['content-type']).toContain('xml')

  const xml = await response.text()
  expect(xml).toContain('<loc>https://event-junkie.de/en</loc>')
  expect(xml).toContain('<loc>https://event-junkie.de/de/legal/imprint</loc>')
  // 8 static pages × 2 locales. A change here is a real change to what gets indexed.
  expect(xml.match(/<url>/g)).toHaveLength(16)
})

test('serves a robots.txt that points at the sitemap', async ({ request }) => {
  const response = await request.get('/robots.txt')

  expect(response.status()).toBe(200)
  expect(await response.text()).toContain('Sitemap: https://event-junkie.de/sitemap.xml')
})

test('annotates a page with a canonical URL and reciprocal alternates', async ({ page }) => {
  await page.goto('/de/events')

  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/de/events',
  )
  await expect(page.locator('link[rel="alternate"][hreflang="en"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/en/events',
  )
  // The self-reference: without it the annotation is one-way and gets ignored entirely.
  await expect(page.locator('link[rel="alternate"][hreflang="de"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/de/events',
  )
  await expect(page.locator('link[rel="alternate"][hreflang="x-default"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/en/events',
  )
})

test('tags the Open Graph locale and its alternate', async ({ page }) => {
  await page.goto('/de/about')

  await expect(page.locator('meta[property="og:locale"]')).toHaveAttribute('content', 'de_DE')
  await expect(page.locator('meta[property="og:locale:alternate"]')).toHaveAttribute(
    'content',
    'en_GB',
  )
  await expect(page.locator('meta[property="og:url"]')).toHaveAttribute(
    'content',
    'https://event-junkie.de/de/about',
  )
})

test('drops the query string from the canonical URL', async ({ page }) => {
  // Filters are a client-side refinement of the same list served by the same HTML. Indexing each
  // combination separately would be near-duplicate content, and the filter space is large.
  await page.goto('/en/events?type=CONCERT')

  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/en/events',
  )
})

test('rewrites the annotations on in-app navigation without accumulating them', async ({
  page,
}) => {
  // An SPA navigates without reloading, so nothing clears the head between routes. Two canonical
  // tags are worse than none — a crawler has no way to choose.
  await page.goto('/en')
  await page.getByRole('navigation', { name: 'Main' }).getByRole('link', { name: 'Venues' }).click()
  await expect(page).toHaveURL(/\/en\/venues$/)

  await expect(page.locator('link[rel="canonical"]')).toHaveCount(1)
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/en/venues',
  )
  await expect(page.locator('link[rel="alternate"]')).toHaveCount(3)
  await expect(page.locator('meta[property="og:locale:alternate"]')).toHaveCount(1)
})

test('annotates the destination of a redirect, not the URL that was requested', async ({
  page,
}) => {
  // `/venues` redirects to `/en/venues`. Annotating the pre-redirect URL would name a redirect as
  // canonical, which is self-defeating.
  await page.goto('/venues')

  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
    'href',
    'https://event-junkie.de/en/venues',
  )
})
